### ISSUE TITLE
Document that a c compiler is required for installation

### ISSUE THREAD

**Issue by Azeirah** [tree-sitter/py-tree-sitter#1]
```
pip install tree_sitter
```

```
...snipped...
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Itree_sitter/core/lib/include -Itree_sitter/core/lib/utf8proc -Ic:\users\laura\appdata\local\programs\python\python37\include -Ic:\users\laura\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tctree_sitter/core/lib/src/lib.c /Fobuild\temp.win-amd64-3.7\Release\tree_sitter/core/lib/src/lib.obj -std=c99
    error: command 'cl.exe' failed: No such file or directory
```

I think it should be included in the docs that Visual Studio is a dependency for installing tree_sitter

**Comment by maxbrunsfeld** [comment]
That seems reasonable. It seems like there are a lot of popular python packages that have C/C++ components. Is there a common way of indicating this in the documentation? I'd be open to a PR updating the docs.

**Comment by brupelo** [comment]
Pointing out to the the docs at [https://docs.python.org/3.6/distutils/apiref.html#distutils.ccompiler.new_compiler](https://docs.python.org/3.6/distutils/apiref.html#distutils.ccompiler.new_compiler) may be reasonable... or even the source code may also be good as well [https://github.com/python/cpython/blob/master/Lib/distutils/ccompiler.py#L957-L970](https://github.com/python/cpython/blob/master/Lib/distutils/ccompiler.py#L957-L970)

**Comment by maxbrunsfeld** [comment]
I put a note about a C compiler in the README.
