### ISSUE TITLE
Why is the match API not implemented?

### ISSUE THREAD

**Issue by zjlariel** [tree-sitter/py-tree-sitter#108]
I want to get the matches of query result rather than captures, but the python binding seems not implementing this API.
And the rust binding seems working well. Why python not implement it?
![image](https://user-images.githubusercontent.com/90076400/167061871-cda080ec-d5af-45b6-9fed-c595a160a1ff.png)

**Comment by synek** [comment]
+1 I was hoping to see the match API here too

**Comment by HALOCORE** [comment]
+1 hope to use this `matches` API, but currently not implemented.

**Comment by leotrs** [comment]
+1
