### ISSUE TITLE
Type Providers

### ISSUE THREAD

**Issue by wenkokke** [tree-sitter/py-tree-sitter#116]
Just wanted to point you to [wenkokke/py-tree-sitter-type-provider](https://github.com/wenkokke/py-tree-sitter-type-provider), which:

- generates dataclasses from a `node-types.json` file,
- provides a conversion from `tree_sitter.Node` to those dataclasses, and 
- provides a generic visitor and transformation patterns.

For an example of how to use it, see [wenkokke/py-tree-sitter-talon](https://github.com/wenkokke/py-tree-sitter-talon).

**Comment by ObserverOfTime** [comment]
If the project is still maintained we can mention it when we update the docs.
