### ISSUE TITLE
Unreleased tree-sitter segfaults python when exiting

### ISSUE THREAD

**Issue by Akuli** [tree-sitter/py-tree-sitter#118]
On linux:

```
$ cd /tmp
$ python3.9 -m venv e
$ . e/bin/activate
(env)$ pip install git+https://github.com/tree-sitter/py-tree-sitter
...
(env)$ python3 -c 'import tree_sitter'
Segmentation fault
```

I bisected. 3ab3d45d6fa16641c3a62356d98290ae4cfa4ab8 is the first bad commit, so the latest release on pypi (v0.20.0) is still good.

**Comment by lunixbochs** [comment]
I updated the ASAN CI build to catch this and also fixed the segfault in c3e071b

**Comment by Akuli** [comment]
I don't really like c3e071b. If `PyModule_AddObject` fails (although that's quite unlikely), it just keeps going and potentially returns a half-initialized module. It won't segfault, but it would cause pretty weird `AttributeError`s.

**Comment by Akuli** [comment]
Looking at the rest of the function, it also leaks memory in the various `return NULL`s it has. Maybe "perfect error handling correctness" isn't exactly what this project's coding style aims for, and it's more like "doesn't segfault in error cases" / "good enough". Sorry for the noise :)

**Comment by lunixbochs** [comment]
I don't think leaking a small amount of memory on `ImportError` here is a particularly big issue, at that point the whole module/program is probably broken anyway. I agree `PyModule_AddObject` should pass the error out, it's still pretty early in the morning for me.

**Comment by lunixbochs** [comment]
I'm tempted to lean into it and say "we will continue to leak on ImportError, because ImportError is likely critical anyway" and add the attributes like this for now, until someone has a better idea that doesn't make maintaining the init function too complicated:
```c
if (   (PyModule_AddObject(module, "Tree", (PyObject *)state->tree_type) < 0)
    || (PyModule_AddObject(module, "TreeCursor", (PyObject *)state->tree_cursor_type) < 0)
    || (PyModule_AddObject(module, "Parser", (PyObject *)state->parser_type) < 0)
    || (PyModule_AddObject(module, "Node", (PyObject *)state->node_type) < 0)
    || (PyModule_AddObject(module, "Query", (PyObject *)state->query_type) < 0)
    || (PyModule_AddObject(module, "Range", (PyObject *)state->range_type) < 0)
    || (PyModule_AddObject(module, "QueryCapture", (PyObject *)state->query_capture_type) < 0)
    || (PyModule_AddObject(module, "CaptureEqCapture", (PyObject *)state->capture_eq_capture_type) < 0)
    || (PyModule_AddObject(module, "CaptureEqString", (PyObject *)state->capture_eq_string_type) < 0)
    || (PyModule_AddObject(module, "CaptureMatchString", (PyObject *)state->capture_match_string_type) < 0)) {
    return NULL;
}
```

**Comment by lunixbochs** [comment]
Alright, I think I found a middle ground by simulating Python 3.10's PyModule_AddObjectRef and making sure to dealloc our module on failure. @Akuli mind reviewing a736793e1f73f37cbece8f3918f8e4d06554c870?

**Comment by Akuli** [comment]
I left a comment to that commit. Some other thoughts:
- `goto cleanup;` together with `Py_XDECREF` is IMO a good approach for not-trivially-small functions that need to do cleanup. For small functions, it's easier to just decref/free everything with if statements.
- I agree that leaking on `ImportError` is not at all critical. A user is very unlikely to try re-importing so many times that the leak would be noticeable.
- Reference counting is hard :) I have spent a lot of time finding that one missing incref/decref in the past (although not with the Python interpreter).

**Comment by lunixbochs** [comment]
I've pushed my changes to master
