### ISSUE TITLE
OSError: my-languages.so is not a mach-o file

### ISSUE THREAD

**Issue by mirzayaser3** [tree-sitter/py-tree-sitter#119]
When I use the tree_sitter, I am getting OSError: (not a mach-o file).
I have attached the image that the library uses the .so file but in mac .so files do not open/ execute. Is there any alternate code that I can run on macOS?

The present code where the .so file lies is attached.
![image](https://user-images.githubusercontent.com/53065667/187000603-ef5dbfcc-2618-473e-b270-f03dca58fb76.png)

**Comment by amaanq** [comment]
you need to compile it yourself as a proper mach-o file, I'm guessing you are pulling pre-built parsers someone built on a Linux machine
