### ISSUE TITLE
README: should we mention py-tree-sitter-languages?

### ISSUE THREAD

**Issue by Akuli** [tree-sitter/py-tree-sitter#120]
https://github.com/grantjenks/py-tree-sitter-languages distributes language binaries for py-tree-sitter. Together with #117, they make it possible to use py-tree-sitter without having a C compiler installed.

We should probably update our README to mention this possibility, as it currently claims that "you do need to have a C compiler installed". I don't want to do it in #117 because that PR is already big enough.

**Comment by ObserverOfTime** [comment]
Parsers can now easily build wheels themselves with the updated bindings in https://github.com/tree-sitter/tree-sitter/commit/9e5bf6591fbf69f7cf79d178e4bcae98408bae40.
