### ISSUE TITLE
ModuleNotFoundError: No module named 'tree_sitter.binding'

### ISSUE THREAD

**Issue by songhuan541** [tree-sitter/py-tree-sitter#123]
![image](https://user-images.githubusercontent.com/114461981/203938905-f149c70c-1098-4112-ae6d-1be132282391.png)

**Comment by thepurpleowl** [comment]
Are you getting this with `pip install`? Any chance you're missing [isuue #84 ](https://github.com/tree-sitter/py-tree-sitter/issues/84)?
