### ISSUE TITLE
Different version than what's installed via npm?

### ISSUE THREAD

**Issue by leotrs** [tree-sitter/py-tree-sitter#124]
I am currently developing a tree-sitter grammar for a custom language. I am getting different results from `tree-sitter parse <path>` (installed via npm) and when running `tree_sitter.Parser().parse(src)` from python. All I can think of is that py-tree-sitter may be using a different version of tree-sitter than what's installed via npm.

My version of py-stree-sitter is
```
$ pip freeze | grep tree
tree-sitter==0.20.1
```

And my version of the node cli utility
```
$ cat package.json 
{
  "devDependencies": {
    "tree-sitter-cli": "^0.20.7"
  },
  "main": "bindings/node"
}
```

Are these versions supposed to match? If so, is there a timeline for when I should expect py-tree-sitter 0.20.7?

**Comment by leotrs** [comment]
Bump! :)

**Comment by amaanq** [comment]
No the versions (usually) shouldn't match, and they generally won't. But, parsing results shouldn't be different, an example w/ a public repo would be insightful
