### ISSUE TITLE
How to run on debug mode

### ISSUE THREAD

**Issue by leotrs** [tree-sitter/py-tree-sitter#125]
When calling `p = tree_sitter.Parser(); p.set_language(...); p.parse(...)`, is there some way to imitate the behavior of the `-d` flag in the cli `tree-sitter parse <file> -d`? i.e. how to show all debug messages?

**Comment by leotrs** [comment]
Any input appreciated!

**Comment by amaanq** [comment]
I'm a bit unsure why you'd want that here, but it's not a bad thing. It's typically used for grammar development, which has no relation to the python bindings

**Comment by ObserverOfTime** [comment]
Yes, you should use the CLI for debugging.
