### ISSUE TITLE
Python simple match, case statement causes error in newest version

### ISSUE THREAD

**Issue by osheratias** [tree-sitter/py-tree-sitter#126]
Any python code that includes "match X:" and/or "case X:" results with an error.
To re-create simply go to: https://tree-sitter.github.io/tree-sitter/playground -> 
select "python" in "code" combo box, then input a code with match, case statement. for example:
```
p: str = "hi"
match p:
  case "hello":
     print "its hello"
```

**Comment by lunixbochs** [comment]
I think you need to file this in https://github.com/tree-sitter/tree-sitter-python not py-tree-sitter. The former is where the Python grammar is defined.
