### ISSUE TITLE
How to modify the tree and get the source code from the ast

### ISSUE THREAD

**Issue by MrBlack0220** [tree-sitter/py-tree-sitter#129]
Hi，
I extract the identifer nodes from the tree.  I want to ask if there is any method to modify the identifer node's text(e.g. change ''a= b+c'' to ''var1 = var2 +var3'').  
And getting the root node, is there any python API to get the source code from the tree? It's becaues after I change the nodes of the tree，I want to get the new code of the new tree.

**Comment by leotrs** [comment]
Each node of the tree stores the starting and ending points in the source code they correspond to, but you won't get the actual source code from the tree itself. Try `node.start_point` and `node.end_point`.

**Comment by MrBlack0220** [comment]
Thanks!

**Comment by Elendor11** [comment]
I'm using TreeSitter in a similar capacity at the moment, and like @leotrs says it's indeed possible to use the `node.startpoint` or `node.start_byte`. I did however had to add the whitespaces and newlines etc myself as they aren't nodes on the AST.

**Comment by amaanq** [comment]
use `tree.edit` then check the nodes again
