### ISSUE TITLE
Node types across multiple grammars

### ISSUE THREAD

**Issue by Elendor11** [tree-sitter/py-tree-sitter#130]
I'm using Tree-sitter to be able to parse many different languages to ASTs in my program.
An issue I'm facing is that the grammars don't seem to have a universal way of naming node types.
For example a string literal node doesn't have the same type name for the Python grammar as for the C++ grammar.
Perhaps there is information in the grammar I'm overlooking, but I'm wondering if there is any way to easily find what name a grammar uses for a certain node type?
Right now I'm adding the different node type names manually, or looking for keywords such as 'identifier'.

**Comment by leotrs** [comment]
Different language grammars are developed in entirely different repositories, usually by entirely different people. Perhaps there could be some coordination among some of the more "official" grammars, but I wouldn't hold my breath unfortunately?

I believe there is *some* of this in terms of how the highlighting queries are designed, but I forget where I read about this :eyes:

**Comment by Elendor11** [comment]
That's what I thought up to now too, so my current solution is have simple configurations for each language grammar, describing how the node types I need are named in the grammar.

I'll see if I can find any information in how the highlighting queries are designed though, thanks!

**Comment by amaanq** [comment]
This is intentional, no two languages are the same. For that, you can collect queries for different languages and unify a capture group to signify a certain "node type" you want, like identifiers, fields, functions, etc. 

You can of course take inspiration from upstream queries and/or nvim-treesitter's queries
