### ISSUE TITLE
can not extract string of the bash script

### ISSUE THREAD

**Issue by riusksk** [tree-sitter/py-tree-sitter#131]
the base script:
`printf "[!] Apache Tomcat for *nix\n[!] Usage: $0 server port\n"`

python code with tree-sitter-bash for parsing the above script:
```
def traver_nodes(root_node):
    children = root_node.children
    if not children:
        print(f'{root_node.type}: {root_node.text}')
    
    for child in children:
         traver_nodes(child)

parser = Parser()
parser.set_language(BASH_LANGUAGE)
tree = parser.parse(bytes(code, "utf-8"))
traver_nodes(tree.root_node)
```

output:

> word: printf
> ": "
> $: $
> special_variable_name: 0
> ": "
> 
> : 

The above output does not get the string "Apache Tomcat ..."
Is this a bug in tree-sitter-bash, or is my python code incorrect?

**Comment by liangyingshao** [comment]
I'm having the same problem, have you solved it yet?
