### ISSUE TITLE
Incompatible Language version 11. Must be between 13 and 14

### ISSUE THREAD

**Issue by Raj-Vir** [tree-sitter/py-tree-sitter#134]
Hi, I'm facing issue "compatibility error"
have latest version of tree-parser 
!pip3 install tree_sitter==0.20.1

Language.build_library(
  // Store the library in the `build` directory
  'my-languages.so'
  // Include one or more languages
  [
    'tree-sitter-python'
  ]
)

PY_LANGUAGE = Language('parser/my-languages.so','python')
    parser = Parser()
    parser.set_language(PY_LANGUAGE)

**Comment by YuJieF** [comment]
I am facing the same question and I tried solutions mentioned in the closed issues.

**Comment by visrut-at-incubyte** [comment]
try to use this library: https://github.com/microsoft/CodeBERT/blob/master/GraphCodeBERT/codesearch/parser/my-languages.so

**Comment by amaanq** [comment]
parser version is too old, you need to rebuild it
