### ISSUE TITLE
Objects are not writable

### ISSUE THREAD

**Issue by stukec0** [tree-sitter/py-tree-sitter#136]
Hay,

My goal is to have a input source code, parse it to a tree, edit variable names, parse it pack to code.
So, I want to modify the texts in the nodes, which is sadly not possible:
`AttributeError: attribute 'text' of 'tree_sitter.Node' objects is not writable`
Is their a workaround? Some method how I can disable it or parse the Tree to a dict and then to a Tree again?

Thanks in advance! :)

**Comment by amaanq** [comment]
use `tree.edit` to edit the text

**Comment by jmehnle** [comment]
Actually, `Tree.edit` cannot modify the actual source text, because this method doesn't accept any actual text arguments. You need to edit your own copy of the source text separately from any `Tree.edit` calls you may do.
