### ISSUE TITLE
Failed to convert some C expressions to the syntax tree.

### ISSUE THREAD

**Issue by xiaoluo012** [tree-sitter/py-tree-sitter#147]
![image](https://github.com/tree-sitter/py-tree-sitter/assets/18416687/bc6c0168-7f4c-49ee-933b-773461f94b9e)
![image](https://github.com/tree-sitter/py-tree-sitter/assets/18416687/bbc4a383-9e6d-439a-9ca3-31cd0a909099)
![image](https://github.com/tree-sitter/py-tree-sitter/assets/18416687/fae1624a-95ab-420b-8f1c-5e01c9b21101)

**Comment by amaanq** [comment]
wrong repo, and frankly it's just a limitation of pure ambiguity in C, it could be correct depending on the type of the identifier, which tree-sitter cannot know but a compiler/lsp like clang/clangd can.
