### ISSUE TITLE
New tag and PyPi release?

### ISSUE THREAD

**Issue by ericwb** [tree-sitter/py-tree-sitter#149]
Can we get a new tag that incorporates the latest tree-sitter and published to PyPI? I'm looking for a number of fixes that appear to be in later versions of the base tree-sitter.
Thanks!

**Comment by ofek** [comment]
@amaanq Do you have an estimate on when the next release might be? We are waiting on the wheels that are now built https://github.com/tree-sitter/py-tree-sitter/pull/117

Unfortunately we cannot use this library until then because our users do not have compilers usually.

**Comment by amaanq** [comment]
I released 0.20.2 with a plethora of api changes, have fun :smile:

**Comment by darrenburns** [comment]
Amazing - thanks so much!!
