### ISSUE TITLE
Getting nodes by position

### ISSUE THREAD

**Issue by andymass** [tree-sitter/py-tree-sitter#15]
It is great to see the py binding is getting better with your recent addition of tree-queries, etc.  Thank you for your efforts!

It would also be useful if node searches by position could be supported, i.e., `*descendant_for_*_range` / `first_*_child_for_byte`.

**Comment by sogaiu** [comment]
@andymass I made an attempt at bindings for the 2 `first_*_child_for_byte` functions here: https://github.com/sogaiu/py-tree-sitter/tree/first-child-for-byte

**Comment by sogaiu** [comment]
I added an attempt at the 2 `*descendant_for_byte_range` functions in the same branch.

In the process of writing tests for the 4 functions done so far I confirmed that I don't understand how they are supposed to work :)

I tried searching for usages and came up empty-handed.
