### ISSUE TITLE
py-tree-sitter 0.20.2 requires unrelease header version from tree-sitter

### ISSUE THREAD

**Issue by arthurzam** [tree-sitter/py-tree-sitter#151]
In the C file, we are using `TSLookaheadIterator`:

https://github.com/tree-sitter/py-tree-sitter/blob/0e573fed2e4705152f72cc7906c5055289f2a8d9/tree_sitter/binding.c#L73

But this was added to "tree_sitter/api.h" file only in https://github.com/tree-sitter/tree-sitter/commit/c47e217e7303c704d2cb88ced1b2720f15a2d949, as in this [diff](https://github.com/tree-sitter/tree-sitter/commit/c47e217e7303c704d2cb88ced1b2720f15a2d949#diff-3f09008ac6c49409e788d7e5b7661e739be000de93886ae80f1f8af648c210a1).

This isn't released yet, so we can't build this package on gentoo.

-----

I've tested a fix, by a stupid addition at the beginning of the C file (after includes) of:

```c
typedef struct TSLookaheadIterator TSLookaheadIterator;
```

And now it compiles.

-----

Would it be possible to fix it and release a new version :)

**Comment by arthurzam** [comment]
Now after passing compilation, I now have runtime error with lib-tree-sitter-0.20.8:

```
 * python3_10: running distutils-r1_run_phase python_test
python3.10 -m unittest_or_fail discover -v
tests.test_tree_sitter (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests.test_tree_sitter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_tree_sitter
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/var/tmp/portage/dev-python/tree-sitter-0.20.2/work/py-tree-sitter-0.20.2/tests/test_tree_sitter.py", line 6, in <module>
    from tree_sitter import Language, Parser, Tree
  File "/var/tmp/portage/dev-python/tree-sitter-0.20.2/work/py-tree-sitter-0.20.2-python3_10/install/usr/lib/python3.10/site-packages/tree_sitter/__init__.py", line 12, in <module>
    from tree_sitter.binding import (LookaheadIterator, Node, Parser,  # noqa: F401
ImportError: /var/tmp/portage/dev-python/tree-sitter-0.20.2/work/py-tree-sitter-0.20.2-python3_10/install/usr/lib/python3.10/site-packages/tree_sitter/binding.cpython-310-x86_64-linux-gnu.so: undefined symbol: ts_node_descendant_count
```

This was added in commit https://github.com/tree-sitter/tree-sitter/commit/9dd725b4e3945cd36d70792327c16beeec0204e9, in [diff](https://github.com/tree-sitter/tree-sitter/commit/9dd725b4e3945cd36d70792327c16beeec0204e9#diff-3f09008ac6c49409e788d7e5b7661e739be000de93886ae80f1f8af648c210a1). Also sadly unreleased :(

**Comment by amaanq** [comment]
Yeah I want to release a new version of `tree-sitter` but there's a couple blockers atm, hopefully soon
