### ISSUE TITLE
Version `0.20.2` includes breaking changes

### ISSUE THREAD

**Issue by wenkokke** [tree-sitter/py-tree-sitter#152]
The recent `0.20.2` includes breaking changes.

The method `current_field_name` was turned into a property between `0.20.1` and `0.20.2`.

![IMG_3267](https://github.com/tree-sitter/py-tree-sitter/assets/3983973/c72b4c94-aad0-4602-b9b5-c752b6a17101)
![IMG_3268](https://github.com/tree-sitter/py-tree-sitter/assets/3983973/bcc0e39e-c0b1-4b0f-bdda-9424fdb263f7)

The other methods that are now accessors are also breaking changes.

Version `0.20.2` should probably be yanked, with these changes either reverted or republished under a major version increase?

**Comment by amaanq** [comment]
Sorry, tree-sitter's versioning scheme is not like semantic versioning (though I myself would like it to be), that's just how the creator wants it done. 

Any release is to be considered a decently big one here and in the main repo

**Comment by wenkokke** [comment]
Please edit the project readme to add that any version change should be considered breaking.

Any past release that worked under the reasonable assumption that the `X.Y.Z` scheme of tree-sitter follows the standard Python `major.minor.micro` semantics is now permanently broken.

**Comment by wenkokke** [comment]
I've filed #153 to request this change.
