### ISSUE TITLE
Add warning that `py-tree-sitter` versions don’t follow SemVer

### ISSUE THREAD

**Issue by wenkokke** [tree-sitter/py-tree-sitter#154]
Please edit the project readme to add a warning that `py-tree-sitter` versions don’t follow SemVer and any version change should be considered breaking.

Any past release that worked under the reasonable assumption that the `X.Y.Z` scheme of tree-sitter follows the standard Python `major.minor.micro` semantics will permanently break when a new version of `py-tree-sitter` is released, with no way of addressing the issue.

**Comment by pokey** [comment]
I totally agree that it is painful to introduce a backwards incompatible change in a patch version, but I don't think that's in violation of semantic versioning when the major version is 0. From the [semantic versioning spec](https://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

That being said, I don't think it hurts to have a note somewhere in the readme to remind people of that fact
