### ISSUE TITLE
Why is the type of my file ERROR? What's wrong with it?

### ISSUE THREAD

**Issue by zndqs** [tree-sitter/py-tree-sitter#155]
![image](https://github.com/tree-sitter/py-tree-sitter/assets/99935313/e6af3c0f-a862-4f58-9486-c98c0805fec9)

[a.txt](https://github.com/tree-sitter/py-tree-sitter/files/12595955/a.txt)

**Comment by amaanq** [comment]
The screenshot and file are not really helpful at all, provide a minimal reproducer + the language used
