### ISSUE TITLE
How to Determine the Params for tree.edit(...)

### ISSUE THREAD

**Issue by tarsur909** [tree-sitter/py-tree-sitter#156]
I have some python code stored as a bytes object in the format:
```python  
source_code = """
def foo():
    if bar:
        baz()
"""
src = bytes(source_code)
tree = parser.parse(src)
 ```
I want to add one token at a time to the end of `source_code` and update the parse tree incrementally without having to run from scratch. I see the that tree-sitter has a tree.edit(...) function which allows the syntax tree to be edited. 
```python  
tree.edit(
    start_byte= ?,
    old_end_byte= ?,
    new_end_byte= ?,
    start_point=(?, ?),
    old_end_point=(?, ?),
    new_end_point=(?, ?),
)
 ```
 How do I determine what to pass into tree.edit(...)?

**Comment by amaanq** [comment]
byte is the unicode code point, point is the row, column a a 2-pair tuple of ints, you indicate the old range that you want to edit, then pass in the new ending byte and point to indicate if you've added code or removed code - you then update the source code reflecting this edit, and reparse by passing in the new source code with the old tree. 

Take a look in the tests to see some examples
