### ISSUE TITLE
get an ast with identifier values

### ISSUE THREAD

**Issue by fengzhangyin** [tree-sitter/py-tree-sitter#16]
This is a awesome project.

I'm not familiar with this tool. Now all identifiers are replaced by the same word. I want to get an ast with  identifier values, but I don't know how to do it.

**Comment by maxbrunsfeld** [comment]
Currently, the way to get the *text* for an ast node is to use the `Node.start_byte` and `node.end_byte` properties:

```py
tree = parser.parse(source_code_bytes)

# ...

text = source_code_bytes[node.start_byte:node.end_byte]
```

Does that help? I think it'd be possible to add a more convenient API also, but I'm not sure what it should be.

**Comment by fengzhangyin** [comment]
@maxbrunsfeld 

Very good. My problem has been solved.  Thank you very much.

I think you can add an attribute to identifier node to get the text of the node. Because identifier node text  is a user-defined value,  getting this value may be more useful. 
I  just put forward my opinion. You can think about it again.

**Comment by AlexGustafsson** [comment]
Would it be possible to support a `.text` property as is done in the JavaScript bindings?

**Comment by sogaiu** [comment]
Regarding `.text` for nodes, roughly, I think the way it is done in node-tree-sitter is something like:

* When a SyntaxNode is created, it is passed a tree in its constructor: https://github.com/tree-sitter/node-tree-sitter/blob/209e734e8df0bc0b79ef0af222843a92ce9c5c8c/index.js#L47-L50

* If the node's `.text()` is used, the associated tree's `.getText()` is called: https://github.com/tree-sitter/node-tree-sitter/blob/209e734e8df0bc0b79ef0af222843a92ce9c5c8c/index.js#L76-L78

* That `.getText()` was arranged for when `parse` was called to create the tree that the node is a part of -- if it was a string that was parsed, this is retained as part of the tree: : https://github.com/tree-sitter/node-tree-sitter/blob/209e734e8df0bc0b79ef0af222843a92ce9c5c8c/index.js#L271-L293

That's not the whole story it seems, but at any rate, it gives some idea of possibly what could be done in the case of py-tree-sitter.

**Comment by majkrzak** [comment]
Is there any plan about it? I can handle the implementation.

**Comment by sogaiu** [comment]
I was working on something in #36, but am not attached to it.

I don't know if anyone else is working on something.

If you do end up going ahead with something and haven't looked at the discussion in #36, I think it might be good to take a look.

**Comment by majkrzak** [comment]
I'll get through it and let you know

**Comment by bdqnghi** [comment]
any update on this matter, can we use the .text to get the identifier value now?

**Comment by lunixbochs** [comment]
node.text was recently merged, it should work on HEAD
