### ISSUE TITLE
Provide wheels for linux arm64/aarch64

### ISSUE THREAD

**Issue by djmattyg007** [tree-sitter/py-tree-sitter#160]
Would it be much effort to provide wheels for 64-bit Arm on Linux?

Textual now has a hard dependency on this library, which will mean more people than ever are trying to get this library installed on M1 machines inside of Docker (which runs a Linux VM on macOS).

**Comment by amaanq** [comment]
Sure why not

**Comment by amaanq** [comment]
I released 0.20.3 but fumbled the CI action so wheels weren't available on PyPI - 0.20.4 is now fixed with wheels on GH releases and PyPI
