### ISSUE TITLE
Swift: Incompatible Language Version 10. Must be between 13 and 14

### ISSUE THREAD

**Issue by chengtianxing** [tree-sitter/py-tree-sitter#166]
Try to parse the [swift language](https://github.com/alex-pinkus/tree-sitter-swift) but getting the following error when setting up the language:
```
parser = Parser()
parser.set_language(SWIFT_LANGUAGE)
```

`ValueError: Incompatible Language version 10. Must be between 13 and 14`

**Comment by amaanq** [comment]
you need to use tree-sitter cli on stable or master and then regenerate your swift parser file.
