### ISSUE TITLE
Special case not managed by the parser, when an expression is split without a backslash and the second line is dedented.

### ISSUE THREAD

**Issue by martinett** [tree-sitter/py-tree-sitter#179]
Here is a minimal valid python code sample for the parser to detect an error :
```python
if True:
    l[i+
1]
```

And here is a minimal code to get the error :
```python
from tree_sitter import Language, Parser

Language.build_library("build/my-languages.so", ["parsers/tree-sitter-python"])
PY_LANGUAGE = Language("build/my-languages.so", "python")
parser = Parser()
parser.set_language(PY_LANGUAGE)

code = "if True:\n    l[i+\n1]"
tree = parser.parse(bytes(code,"utf-8"))
print(tree.root_node.sexp())
print(tree.root_node.children[1])
print(tree.root_node.children[0].children[3])
```
```
(module (if_statement condition: (true) (ERROR (identifier) (identifier)) consequence: (block)) (ERROR (integer)))
<Node type=ERROR, start_point=(2, 0), end_point=(2, 2)>
<Node type=ERROR, start_point=(1, 4), end_point=(1, 8)>
```

Whatever the indentation of the `1]` line, if it is less indented than the `l[i+` line, the parser detects an error.
But this code is valid, it works and the ast library has no problem parsing it.

**Comment by martinett** [comment]
I don't think it is a parser python version problem, but I couldn't find how to check this.

**Comment by martinett** [comment]
So there is no solution to this? I can't deal with codes which contain this pattern.

**Comment by amaanq** [comment]
it is a parser error, feel free to PR a fix yourself in the parser repo
