### ISSUE TITLE
The Python parser appears to be parsing comments and strings with unmatched parentheses as code

### ISSUE THREAD

**Issue by fbunt** [tree-sitter/py-tree-sitter#199]
I just ran into this problem while editing below a docstring that has an opening parenthesis but not a paired closing parenthesis. The docstring is being parsed as if it were regular code and the result is that auto indenting is very confused for everything after the string. I did some testing and it happens for comments, too. I think I've narrowed it down to a minimal config that reproduces the issue.

**init.lua**

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function()
            require("nvim-treesitter.configs").setup({
                -- A list of parser names, or "all". These will be installed immediately.
                ensure_installed = { "python" },
                auto_install = true,
                highlight = {
                    enable = true,
                    additional_vim_regex_highlighting = false,
                },
            })
        end,
    },
}, {})
```

**test.py**
```python
# (
```

In normal mode with the cursor on the comment line in `test.py`, pressing \<o\> to enter edit mode on the next line results in the cursor moving to the next line but with multiple indent levels being applied. If I set `additional_vim_regex_highlighting=true` in the config above, the issue goes away.

Version info:
* Neovim: 0.9.4
* Python: 3.10.13
* Latest for everything else

**Comment by maxbrunsfeld** [comment]
Can you open this issue on Neovim, or nvim-tree-sitter? This repository is for a python library that provides bindings to Tree-sitter.

**Comment by fbunt** [comment]
Whoops! Sorry for the mixup. Will do.
