### ISSUE TITLE
Broken (?) README instructions to pip install pre-compiled binary wheels

### ISSUE THREAD

**Issue by JohnAmadeo** [tree-sitter/py-tree-sitter#207]
README suggests

> Tree-sitter language implementations also provide pre-compiled binary wheels. Let's take [Python](https://github.com/tree-sitter/tree-sitter-python) as an example.
> `pip install tree-sitter-python`

But running `pip install tree-sitter-python` returns the following error:
> ERROR: Could not find a version that satisfies the requirement tree-sitter-python (from versions: none)
ERROR: No matching distribution found for tree-sitter-python

I looked on pypi, and indeed no such package seems to exist (https://pypi.org/search/?q=tree-sitter-python&o=)

What is the recommended setup method now? Given that the README also mentions the other method (building from source) is "deprecated and will be removed in v0.22.0"

Thanks!

**Comment by ObserverOfTime** [comment]
It will be published soon.
