### ISSUE TITLE
Make TreePropertyCursor Object available

### ISSUE THREAD

**Issue by anandsork** [tree-sitter/py-tree-sitter#21]
Can TreePropertyCursor be made accessible along with TreeCursor? It seems to have useful functionality. 
If one can give me pointers, I can try to add the bindings.
I saw it at https://github.com/tree-sitter/rust-tree-sitter/blob/375e6b4b59961da4d62db1dda90c99263d1abfdc/src/lib.rs.
The usage I saw was at https://github.com/maxbrunsfeld/tree-tags/blob/master/src/crawler.rs.. Here, the propertyMatcher is used to find the scope_type, definition etc.. 
I would like to get the scope of any variable/identifier I am encountering in the AST.. From these examples, I got the impression that tree_sitter has some kind of book-keeping for it.

**Comment by maxbrunsfeld** [comment]
I've gotten rid of the `TreePropertyCursor` and replaced it with a new *tree query* API. There is already a binding for the query API in `py-tree-sitter` although a little bit of functionality is still missing.

Similar to the `TreePropertyCursor`, the purpose of a query is to allow you to look for certain patterns in a syntax tree, and iterate over all of the matches. With the old properties API, you could write the patterns as CSS selectors. But now, with the query API, there is a more general, flexible pattern-matching syntax.

Here are some links that might be helpful:
* tree-sitter/tree-sitter#444 
* tree-sitter/tree-sitter#448
* The [docs](http://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries) on tree queries

If you're interested in tracking scopes and local variables, that can be done with tree queries. The `tree-sitter-highlight` library (introduced in the second PR above) tracks local variables for some languages, if they have a `locals.scm` query file. Here's an example of one: https://github.com/tree-sitter/tree-sitter-ruby/blob/master/queries/locals.scm.

**Comment by anandsork** [comment]
Thanks @maxbrunsfeld .. Will check...

**Comment by anandsork** [comment]
@maxbrunsfeld 
Can we pass the query to parse somehow? I would like to tag few nodes while walking. In Query API way, I have to fire the query everytime in that node (where I expect tagging would occur). 
Instead of highlighting, I would like to have this information while I am walking through the children. Is there any way?

**Comment by maxbrunsfeld** [comment]
You use a query cursor to walk the tree, iterating over the matching nodes. You would no longer walk the tree with the tree cursor.

**Comment by anandsork** [comment]
@maxbrunsfeld 

Not sure how to ask the questions.. So adding a query here

I am trying to find out the member variables (class, instance etc..) of a class. The query I am doing is based on attribute (Self Function calls come as well, but I figured out a way to filter those)..
`
((attribute
  object: (identifier) @obj 
  attribute: (identifier) @property)
  (match? @obj "^self$"))
`

I am able to get most of the variables. 

However the capture also give me inner class attributes as well

1. How can I suppress the captures with a condition (If the indirect parent is a class_def which does not have specific name)?
2. Can I add multiple capture-names (@capture-name)?
I wanted to add a specific capture-name to all identifiers which has the pattern of 
`(class_definition <Anylevel> (class_definition <AnyLevel Identifier> @innerClassIdent))`
If I find `@innerClassIdent` & `@property` both, I might ignore it..
The main problem in above query is `<AnyLevel>`. I am not sure how to find all Identifiers & tag them

**Comment by anandsork** [comment]
I found a wayout. Querying the inner ClassDefinition with the query like below..
(The * has some special significance, it seems.. Even **, *** has some level related meaning. However I could not found the documentation around it)
```
(class_definition
  (* (class_definition (identifier)* @inner) ) )
```
One can get the inner class Node StartPoint & EndPoint.. There are different ways as well (getting child with class_definition type). 
I can then filter the `@property` nodes (retrieved using the query shared in earlier post) with the line number or range.

Not sure if this is optimal way. But it might work I think. Comments welcome.

Thanks..
