### ISSUE TITLE
Remove/replace the usage of distutils

### ISSUE THREAD

**Issue by fabaff** [tree-sitter/py-tree-sitter#213]
`distutils` is deprecated and slated for removal in Python 3.12

https://peps.python.org/pep-0632//#migration-advice

https://github.com/tree-sitter/py-tree-sitter/blob/ce1af663b4dd5b933a81dc893f36cabbef266ac4/tree_sitter/__init__.py#L88-L89

**Comment by ObserverOfTime** [comment]
You don't say.
