### ISSUE TITLE
Missing aarch64 packages for 0.21.x

### ISSUE THREAD

**Issue by bheilbrun** [tree-sitter/py-tree-sitter#215]
Heya py-tree-sitter team,
In pypi, the latest versions of py-tree-sitter appear to be missing aarch64 packages. Previous versions had wheels for this architecture.

Comparing,
* https://pypi.org/project/tree-sitter/0.20.4/#files
* https://pypi.org/project/tree-sitter/0.21.1/#files

There might be others as the former has 75 whl files and the latter has 25, just as a spot check.

Let me know if I can help.

**Comment by ObserverOfTime** [comment]
Fixed in v0.21.2
