### ISSUE TITLE
[tree-sitter-python] No matching distribution found for tree-sitter-python

### ISSUE THREAD

**Issue by kbmlcoding** [tree-sitter/py-tree-sitter#218]
For below issue
https://github.com/tree-sitter/py-tree-sitter/issues/206

Exciting project and i am wondering if there is any planned date of release for tree-sitter-python (so that i could build tree-sitter for one or more supported languages and use/develop AST for give code in python only)

**Comment by ObserverOfTime** [comment]
https://pypi.org/project/tree-sitter-python/

**Comment by kbmlcoding** [comment]
Thank you ..looks like i was getting that error because of absence of wheel for macos-arm..@ObserverOfTime Any plans for macos arm support for wheel file installation?

**Comment by ObserverOfTime** [comment]
That was a mistake in the workflow. You can either wait for the next version or clone the repo and build it locally for now.
