### ISSUE TITLE
match or eq operators in Query are not working for python Bindings

### ISSUE THREAD

**Issue by anandsork** [tree-sitter/py-tree-sitter#22]
I tried to use the query which has the query with matching regex. However those do not seem to be working. They work in playground, but not when running through Python.
I have following code.

```
i = 0
class ArgParser:
    logger = logging.getLogger("ArgParser")
```
I am trying to use the query as below
```
((attribute
    object: (identifier) @cls
   attribute: (identifier) @clsvar
 )
  (match? @cls "^cls$"))
```

When running through python, it gives `getLogger` as `@clsvar` (Ignoring the match condition). However while using the playground, I am getting the correct result. (When I remove the condition of match in playground, I get similar results as in python.. So I thought python binding is not checking the condition)

Is there any wayout?

**Comment by maxbrunsfeld** [comment]
Yeah, these aren’t implemented in python yet. Sorry for not communicating that. Are you Interested in working on it? I could help get you started.

**Comment by anandsork** [comment]
If its not that complex, I can work on it..
I saw https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/binding.js.. Could not understand what step is and how it works.
I assume similar implementation is required in py-tree-sitter\tree_sitter\binding.c

**Comment by anandsork** [comment]
Hi @maxbrunsfeld 
Any inputs?

**Comment by rcshubhadeep** [comment]
Hi @maxbrunsfeld I am also very interested in this feature. If you want, I can also take up the development. Is there somewhere I can get some kind of guide of how to start? Or can you please put some pointers here?

**Comment by maxbrunsfeld** [comment]
That would be awesome! Here are some links that might be helpful:

* [Documentation about the Query API](https://tree-sitter.github.io/tree-sitter/using-parsers#the-query-api)
* [The C header, with comments documenting each function](https://github.com/tree-sitter/tree-sitter/blob/bfeec63d60e64ecbf8d6cbb324fd3f3d32ee2295/lib/include/tree_sitter/api.h#L656-L814)
* In the Rust binding, the code that [finds all of these built-in predicates](https://github.com/tree-sitter/tree-sitter/blob/bfeec63d60e64ecbf8d6cbb324fd3f3d32ee2295/lib/binding_rust/lib.rs#L1240-L1377) and [checks them against each match](https://github.com/tree-sitter/tree-sitter/blob/bfeec63d60e64ecbf8d6cbb324fd3f3d32ee2295/lib/binding_rust/lib.rs#L1593-L1615)
* In the JavaScript/Wasm binding, the code that [finds all of the built-in predicates](https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/binding.js#L719-L842) and [checks them against each match](https://github.com/tree-sitter/tree-sitter/blob/bfeec63d60e64ecbf8d6cbb324fd3f3d32ee2295/lib/binding_web/binding.js#L944-L952)
* [PR to add the Query API to the Node.js binding](https://github.com/tree-sitter/node-tree-sitter/pull/62)

**Comment by rcshubhadeep** [comment]
Hey @maxbrunsfeld Thanks a lot. 

I will keep you posted

**Comment by rcshubhadeep** [comment]
So @maxbrunsfeld Able to set up the environment and also ran the tests successfully. Will be working ahead on this one :) Will keep you posted.

**Comment by rcshubhadeep** [comment]
Hi @maxbrunsfeld I was working on this, but I am a bit lost. I will be straight to the point. I see that all the approaches (rust and js) calls `ts_query_new` in some form an it should return a pointer to TSQuery structure. However, with the following code 

```
        source = b"def SNAKE_CASE():\n  bar()"
        tree = parser.parse(source)
        query = PYTHON.query(
            """
            (
                function_definition name: (identifier) @constant
                (#match? @constant "^[A-Z][A-Z_]+")
            )
            """
        )
```
When it touches these lines in `binding.c`

```
query->query = ts_query_new(
    language, source, length, &error_offset, &error_type
  );
```

It does not seem to be able to produce a proper query. As it goes to the `if (!query->query)` block after this.


So my question is, does it mean that I need to look into `tree-sitter-python` repo first to see if the problem comes from there? Before starting to work with `py-tree-sitter`? As I do not think this work has anything to do in modifying the core `tree-sitter` code. 

Would like to know your opinion about this

Thanks

**Comment by rcshubhadeep** [comment]
@maxbrunsfeld Any thoughts? It would be helpful to know from you before I start a full length investigation. 

Thanks in advance.

**Comment by maxbrunsfeld** [comment]
> It does not seem to be able to produce a proper query

I think you may need to upgrade the `tree_sitter/core` submodule to the latest version of Tree-sitter. The query syntax has [changed](https://github.com/tree-sitter/tree-sitter/pull/615) fairly recently.

**Comment by rcshubhadeep** [comment]
Can you tell me what I need to run for that? I already did a `git submodule upgrade` from my repo (the clone was done from the forked version of me)

**Comment by rcshubhadeep** [comment]
I had done it, The submodule was pointing to 0.16.1 tag, checking out 0.16.8 made it work. Thanks a lot :)
