### ISSUE TITLE
FutureWarning: Language(path, name) is deprecated.

### ISSUE THREAD

**Issue by SunBK201** [tree-sitter/py-tree-sitter#223]
When I use `Language(path, name)` in py-tree-sitter v0.21.3, I get: FutureWarning: Language(path, name) is deprecated. I know this method of loading languages is deprecated and will be removed in v0.22.0. But I need to use tree-sitter-cpp Parser, but at present there is only tree_sitter_python pre-compiled binary wheels.

**Comment by ObserverOfTime** [comment]
tree-sitter/tree-sitter-cpp#250
