### ISSUE TITLE
Deprecation warning `Language.build_library is deprecated. Use the new bindings instead`

### ISSUE THREAD

**Issue by kevinlu1248** [tree-sitter/py-tree-sitter#225]
I'm getting `FutureWarning: Language.build_library is deprecated. Use the new bindings instead. warn("{} is deprecated. Use {} instead.".format(old, new), FutureWarning)`, but I'm not sure where I can find the new bindings.

**Comment by amaanq** [comment]
they should be auto generated when running `tree-sitter generate` in the bindings/python dir. If they're one of the upstream grammars, you can install (most) of them with `pip install tree-sitter-LANG`

**Comment by kevinlu1248** [comment]
Where are the docs for this? @amaanq

**Comment by amaanq** [comment]
did you look at the readme..? https://github.com/tree-sitter/py-tree-sitter?tab=readme-ov-file#install-languages

**Comment by kevinlu1248** [comment]
Oh I see it now, I was using tree-sitter-languages so I got confused, thanks!
