### ISSUE TITLE
Tree sitter gets stuck

### ISSUE THREAD

**Issue by Moddus** [tree-sitter/py-tree-sitter#226]
Hi,

I'm using tree-sitter to parse some scala code using the related grammar from:
https://github.com/tree-sitter/tree-sitter-scala

Please find the related scala sample attached:
[sample.txt](https://github.com/tree-sitter/py-tree-sitter/files/14962211/sample.txt)

Running the code in the snippet below cause the parse to get stuck in an infinite loop, I assume, even if I defined the timeout. Not sure how I could debug the issue or if it's related to tree-sitter itself or the scala grammar.

```python
from tree_sitter import Language, Parser, Range

binary_name = "<path to binary>"
SCALA_LANGUAGE = Language(binary_name, "scala")

parser = Parser()
parser.set_timeout_micros(int(1e6))
parser.set_language(SCALA_LANGUAGE)

with open("sample.txt") as fp:
    scala_code = fp.read()

parser.parse(bytes(scala_code, "utf8"))  # program gets stuck
```

Thanks for you time and suggestions

**Comment by ObserverOfTime** [comment]
You can check if it's related to tree-sitter itself or the scala grammar by renaming `sample.txt` to `sample.scala`
and running `tree-sitter parse sample.scala --timeout 1000000` in the `tree-sitter-scala` folder.

**Comment by ObserverOfTime** [comment]
Which does hang so this is most likely an issue with the grammar and less likely an issue with tree-sitter.

**Comment by Moddus** [comment]
@ObserverOfTime thanks for the insides much appreciated!
