### ISSUE TITLE
Segfaults when accessing nodes and node lists (after tree dealloc)

### ISSUE THREAD

**Issue by yagebu** [tree-sitter/py-tree-sitter#24]
When writing code of the following form I ran into segfaults with py-tree-sitter (I'll also open a PR that reproduces it):

```py
def parse(contents: bytes) -> List[Node]:
    tree = Parser.parse(contents)
    return tree.root_node.children
```

First I tried finding some issue with the creation of the List of child nodes or the nodes itself. Then I realised that this is probably due to the tree going out of scope.

I believe we need to add a reference to the tree (Python object) for every node so that the tree doesn't get destroyed while any of the nodes in the tree are still alive.

**Comment by yagebu** [comment]
Test reproducing this (oddly not in all CI environments) and fixes are in the PR :)

**Comment by maxbrunsfeld** [comment]
Ah yeah, this makes sense. You're right that the nodes need to hold a reference to the tree. For now, the workaround would be to manually ensure that the Tree outlives its nodes.
