### ISSUE TITLE
cannot install the tree-sitter-python using pip

### ISSUE THREAD

**Issue by hminooei** [tree-sitter/py-tree-sitter#247]
When I try `pip install tree-sitter` I get:
```
ERROR: Could not find a version that satisfies the requirement tree-sitter-python (from versions: none)
ERROR: No matching distribution found for tree-sitter-python
```

my python version is 3.12.2

my hardware:
 Model Name:	MacBook Pro
  Model Identifier:	Mac15,7
  Model Number:	MRW23LL/A
  Chip:	Apple M3 Pro
  Total Number of Cores:	12 (6 performance and 6 efficiency)
  Memory:	36 GB
  System Firmware Version:	10151.121.1
  OS Loader Version:	10151.121.1
  Serial Number (system):	J9RJ2TT9G5
  Hardware UUID:	6F728AA1-05A1-57D7-9C9B-6BE36869B8B4
  Provisioning UDID:	00006030-000230963628001C
  Activation Lock Status:	Disabled

**Comment by ObserverOfTime** [comment]
https://github.com/tree-sitter/tree-sitter-python/issues/262
