### ISSUE TITLE
can not install tree-sitter-python on mac m1

### ISSUE THREAD

**Issue by SpeedTest-AI** [tree-sitter/py-tree-sitter#259]
Hi, my computer is mac m1, I can install tree-sitter successfully, but can not install tree-sitter-python. below is details

pip3 install tree-sitter-python
ERROR: Could not find a version that satisfies the requirement tree-sitter-python (from versions: none)
ERROR: No matching distribution found for tree-sitter-python

**Comment by merriam** [comment]
This come up.  The repository is a fake, just an abandoned side project.  They have not released to PyPi.  You will find a few closed issues where they never intend to do so.

**Comment by ObserverOfTime** [comment]
Wrong.
