### ISSUE TITLE
 Unexpected error recovery for python

### ISSUE THREAD

**Issue by bloff** [tree-sitter/py-tree-sitter#26]
Just playing around on the playground (https://tree-sitter.github.io/tree-sitter/playground), the following python code says for is an identifier, and marks x as the error, instead of the other way around.

```python
def func(x, list):
   if for x in list:
      print(x)
```

**Comment by maxbrunsfeld** [comment]
I think https://github.com/tree-sitter/tree-sitter-python/issues/62 is actually the right place for this issue. This repo is just the Python binding to the Tree-sitter library.
