### ISSUE TITLE
MacOS(M3) need a tree-sitter-python

### ISSUE THREAD

**Issue by YolandaLu-coder** [tree-sitter/py-tree-sitter#262]

**Comment by YolandaLu-coder** [comment]
My Computer is MacBook Pro with Apple M3 Pro on Sonoma 14.5.
However, there's no proper tree-sitter-python wheel file for my platform.

**Comment by HolgerZhang** [comment]
According to https://github.com/tree-sitter/tree-sitter-python/issues/262#issuecomment-2077638647 , you can build it from source via pip:

```bash
pip install git+https://github.com/tree-sitter/tree-sitter-python
```
