### ISSUE TITLE
Retrieve the 'name' from a node

### ISSUE THREAD

**Issue by learn-more** [tree-sitter/py-tree-sitter#263]
The function `child_by_field_name()` needs the field name for a node, but this name is very hard to find.

Example:
```py
    parser = Parser(CPP_LANGUAGE)
    tree = parser.parse(b"void test();")
    root = tree.root_node
    print(f'{str(root)=}')
    node = root.child(0)
    # Node is named, but how to get the name?
    print(f'{node.type=}, {node.is_named=}, {node.id=}, {node.kind_id=}, {str(node)=}')
```

All these options do not work:
```py
    print(f'{root.field_name_for_child(0)=}')
    print(f'{CPP_LANGUAGE.field_name_for_id(node.id)=}')
    print(f'{CPP_LANGUAGE.field_name_for_id(node.kind_id)=}')
```
Is there an option I am missing?
Would it make sense to add a `name` field to a node?

**Comment by ObserverOfTime** [comment]
Function naming is inconsistent.
It can be `name`, `kind`, or `type`.

**Comment by ObserverOfTime** [comment]
Node names (`node.type`) and field names are two different things. `field_name_for_id` expects the _field_ id.
