### ISSUE TITLE
Parser logging is not mapped

### ISSUE THREAD

**Issue by learn-more** [tree-sitter/py-tree-sitter#264]
The function [`ts_parser_set_logger`](https://github.com/tree-sitter/tree-sitter/blob/800f2c41d0e35e4383172d7a67a16f3933b86039/lib/include/tree_sitter/api.h#L345) is not available in the `Parser` object.

Is there a reason for this, or is this simply something that is 'not done yet'?

**Comment by ObserverOfTime** [comment]
Not done yet.
