### ISSUE TITLE
ModuleNotFoundError : No Module named 'tree_sitter._binding'

### ISSUE THREAD

**Issue by nevermet** [tree-sitter/py-tree-sitter#280]
I am following the readme page.

I did 
pip install tree-sitter
pip install tree-sitter-python
.

After running this line:
from tree_sitter import Language, Parser
,
I got this message:
ModuleNotFoundError : No Module named 'tree_sitter._binding'
.

Could you tell me how I can resolve this error?

Thanks in advance.

**Comment by ObserverOfTime** [comment]
What's your system?

**Comment by nevermet** [comment]
It's an ubuntu (20.04) with python 3.12.5.

**Comment by nevermet** [comment]
> What's your system?

It's an ubuntu (20.04) with python 3.12.5.

**Comment by ObserverOfTime** [comment]
Post the output of

```
pip install --force-reinstall --verbose tree-sitter
```

**Comment by nevermet** [comment]
> Post the output of
> 
> ```
> pip install --force-reinstall --verbose tree-sitter
> ```

After running the command, following messages came out:
...
    Successfully un-installed tree-sitter-0.22.3
Successfully installed tree-sitter-0.22.3

After this, I could run the import line without any error message. 

Thank you!

**Comment by ppdouble** [comment]
pip3 install --target=/tools/site-packages tree-sitter tree-sitter-python tree-sitter-javascript tree-sitter-typescript tree-sitter-java tree-sitter-cpp tree-sitter-c==0.21.4 tree-sitter-go tree-sitter-rust -i https://mirrors.aliyun.com/pypi/simple/ --upgrade
