### ISSUE TITLE
Parsing invalid using trivial grammar

### ISSUE THREAD

**Issue by brupelo** [tree-sitter/py-tree-sitter#3]
@maxbrunsfeld Hi Max, could you please check this little test?

I'm using latest master of `tree-sitter` and `py-tree-sitter`, both were built ok. And now I try
to use a simple grammar

    (py364_32) d:\mcve>mkdir tree-sitter-hello

    (py364_32) d:\mcve>cd tree-sitter-hello

    (py364_32) d:\mcve\tree-sitter-hello>clipout > grammar.js

    (py364_32) d:\mcve\tree-sitter-hello>cat grammar.js
    module.exports = grammar({
      name: 'the_language_name',

      rules: {
        // The production rules of the context-free grammar
        source_file: $ => 'hello'
      }
    });

    (py364_32) d:\mcve\tree-sitter-hello>tree-sitter generate

    (py364_32) d:\mcve\tree-sitter-hello>cd ..

    (py364_32) d:\mcve>clipout > test.py

    (py364_32) d:\mcve>cat test.py
    from tree_sitter import Language, Parser

    def build():
        Language.build_library(
            'build/parser.pyd',
            [
                "tree-sitter-hello",
            ]
        )

    def main():
        LANGUAGE = Language('build/parser.pyd', 'the_language_name')
        parser = Parser()
        parser.set_language(LANGUAGE)
        tree = parser.parse(bytes("""hello""", "utf8"))

    if __name__ == '__main__':
        build()
        main()

    (py364_32) d:\mcve>python test.py
    parser.c
       Creating library build/parser.lib and object build/parser.exp
    Generating code
    Finished generating code
    Traceback (most recent call last):
      File "test.py", line 21, in <module>
        main()
      File "test.py", line 17, in main
        tree = parser.parse(bytes("""hello""", "utf8"))
    ValueError: Parsing failed

What's the meaning of that "ValueError: Parsing failed"? What am I doing wrong? Do you see anything suspicious here?

Thanks in advance.

**Comment by maxbrunsfeld** [comment]
Try the latest version, 0.0.6. I think there may have been a version mismatch between the Tree-sitter library bundled with `py-tree-sitter` and the version used to generate the latest version of `tree-sitter-python`.

**Comment by brupelo** [comment]
@maxbrunsfeld Updating to `0.0.6` fixed the issue indeed, tyvm!
