### ISSUE TITLE
Text length calculation incorrect for non-English languages

### ISSUE THREAD

**Issue by amalmurali47** [tree-sitter/py-tree-sitter#31]
Since there's no API to access the text right now, we do the following to obtain the text value of a node:

```
tree = parser.parse(source_code_bytes)

# ...

text = source_code_bytes[node.start_byte:node.end_byte]
```

However, this fails if the node text contains a multi-byte character.

## Reproduction
```
from queue import Queue

from tree_sitter import Language, Parser

Language.build_library('build/my-languages.so', ['tree-sitter-javascript'])
JS_LANGUAGE = Language('build/my-languages.so', 'javascript')


parser = Parser()
parser.set_language(JS_LANGUAGE)
code = '''var t = '大';var k=1;'''
code_bytes = bytes(code, "utf8")
tree = parser.parse(code_bytes)
root_node = tree.root_node

queue = Queue()
queue.put(root_node)

while not queue.empty():
    node = queue.get()
    for child in node.children:
        if child.type == 'string':
            print(code[child.start_byte:child.end_byte])
        queue.put(child)
```

### Expected output: 
```
'大';v
```
### Current output: 
```
 '大';
```

If you subtract 2 from `child.end_byte`, it gives the expected result. It would be very much convenient to have a `.text` method or similar to access the text as opposed to accessing it with string slicing.

Please let me know if you need more information.

**Comment by andymass** [comment]
I agree that .text would be highly useful, though

            print(bytes.decode(code_bytes[child.start_byte:child.end_byte]))

gives the correct output per the playground, https://tree-sitter.github.io/tree-sitter/playground

**Comment by maxbrunsfeld** [comment]
Yes, the code in your reproduction script is not correct. You are using the `start_byte` and `end_byte` to slice into a *string*, but that doesn't work: strings are sliced by *character index*, not *byte index*. As @andymass says, you would need to slice the `code_bytes` array.
