### ISSUE TITLE
How to get tree node parent?

### ISSUE THREAD

**Issue by celsofranssa** [tree-sitter/py-tree-sitter#34]
Is there an approach to check node parent?

**Comment by sogaiu** [comment]
From a quick search, it doesn't look exposed via basic functionality, though it looks possible via a cursor:
```
cursor = tree.walk()
cursor.goto_first_child()
cursor.goto_parent()
cursor.node
```
https://github.com/tree-sitter/py-tree-sitter#walking-syntax-trees

On a side note, node-tree-sitter seems to have it: https://github.com/tree-sitter/node-tree-sitter/blob/c40d598b4e3d587c0be26ac6a780d91815ff731a/tree-sitter.d.ts#L52

Perhaps it's not too hard to make this available?

**Comment by sogaiu** [comment]
I don't know how proper the following is, but in limited testing, it seems to work here:
```
diff --git a/tree_sitter/binding.c b/tree_sitter/binding.c
index 2b7b953..674a3f0 100644
--- a/tree_sitter/binding.c
+++ b/tree_sitter/binding.c
@@ -185,6 +185,14 @@ static PyObject *node_get_children(Node *self, void *payload) {
   return result;
 }
 
+static PyObject *node_get_parent(Node *self, void *payload) {
+  TSNode parent = ts_node_parent(self->node);
+  if (ts_node_is_null(parent)) {
+    Py_RETURN_NONE;
+  }
+  return node_new_internal(parent, self->tree);
+}
+
 static PyMethodDef node_methods[] = {
   {
     .ml_name = "walk",
@@ -227,6 +235,7 @@ static PyGetSetDef node_accessors[] = {
   {"start_point", (getter)node_get_start_point, NULL, "The node's start point", NULL},
   {"end_point", (getter)node_get_end_point, NULL, "The node's end point", NULL},
   {"children", (getter)node_get_children, NULL, "The node's children", NULL},
+  {"parent", (getter)node_get_parent, NULL, "The node's parent", NULL},
   {NULL}
 };
```
Basically it just adds a `node_get_parent` function and a corresponding `parent` to `node_methods[]`.

To test this, save the diff to a file (e.g. parent.patch), then in the `py-tree-sitter` directory:
```
git apply parent.patch
```
To verify the patch applied correctly run:
```
git diff
```
That should produce output similar to the content of the patch.

Then to build a customized py-tree-sitter that should be testable within the source directory:
```
python setup.py build_ext --inplace
```

Here I tested the following code (it's likely you'll need to adjust it to use the appropriate language):
```
from tree_sitter import Language, Parser

CLJ_LANGUAGE = Language('build/my-languages.so', 'clojure')

parser = Parser()
parser.set_language(CLJ_LANGUAGE)

source = bytes("^:a [:x]", "utf8")

tree = parser.parse(source)

root_node = tree.root_node

vector = root_node.children[0]

print("parent")

print(vector.parent)
```

**Comment by sogaiu** [comment]
FYI, https://github.com/tree-sitter/py-tree-sitter/pull/35 is a PR that includes code for `parent`.

**Comment by sogaiu** [comment]
The PR mentioned has been merged, so I believe it is now possible to "get tree node parent".
