### ISSUE TITLE
Failed to load tree-sitter-python, but build_library successful

### ISSUE THREAD

**Issue by robobenklein** [tree-sitter/py-tree-sitter#41]
I tried to use the python parser like in the readme example, but I cannot load the built language object file...

```python
from tree_sitter import Language, Parser
Language.build_library('lang.so', ['/home/robo/.cache/wsyntree/python/tsrepo/'])
pylang = Language('./lang.so', 'python')
```
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    pylang = Language('./lang.so', 'python')
  File "/home/robo/.local/lib/python3.8/site-packages/tree_sitter/__init__.py", line 81, in __init__
    self.lib = cdll.LoadLibrary(library_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./lang.so: undefined symbol: _ZSt20__throw_length_errorPKc
```

Since it compiled successfully, I assume it's a problem with py-tree-sitter and not tree-sitter-python (commit `c4282ba` and `4cca050` tested), but I might be wrong since tree-sitter-javascript worked just fine.

I tried both in and outside a virtualenv, on Pop!_OS 20.10, the same example worked without issue on Ubuntu 20.04

Using cc/c++ 10.2.0 on 20.10 and 8.4.0 on 20.04, python 3.8 on both

**Comment by sogaiu** [comment]
What is the output of `ldd langs.so` for the `lang.so` mentioned in the line beginning with `OSError`?

**Comment by robobenklein** [comment]
`lang.so` that failed to load:

	linux-vdso.so.1 (0x00007ffd3b7e7000)
	libc++.so.1 => /lib/x86_64-linux-gnu/libc++.so.1 (0x00007f617cfc3000)
	libc++abi.so.1 => /lib/x86_64-linux-gnu/libc++abi.so.1 (0x00007f617cf8b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f617cf70000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f617cd86000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f617cd64000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f617cc15000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f617cc08000)
	libatomic.so.1 => /lib/x86_64-linux-gnu/libatomic.so.1 (0x00007f617cbfe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f617d0fe000)

**Comment by sogaiu** [comment]
FWIW, here, when I run `ldd` on `python.so` produced via tree-sitter-python, I get:
```
python.so:
	linux-vdso.so.1 (0x00007ffd42531000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f5f417a3000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f5f4165d000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5f41643000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f5f4147a000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f5f419e3000)
```
When I do strings on `/usr/lib/libstdc++.so.6`, I find at least one instance of `_ZSt20__throw_length_errorPKc` (the "undefined symbol" from the `OSError` line).

It looks like in your `ldd` output there is no reference to `libstdc++`.  Possibly no other `.so` in your ldd output has anything relevant for that symbol and consequently `_dlopen` is failing.

May be there was a problem with the creation process of `lang.so`?

On a side note, may be for your Ubuntu environment, the ldd output will mention `libstdc++`.

**Comment by robobenklein** [comment]
Indeed, that was the missing piece, verified it with `LD_PRELOAD="libstdc++.so.6" python` and it worked just fine.

How did it manage to build without linking stdc++?

**Comment by robobenklein** [comment]
I see https://github.com/tree-sitter/py-tree-sitter/blob/master/tree_sitter/__init__.py#L49 which to me sounds like if c++ is used then stdc++ is not included at all.

Is it perhaps that the tree-sitter-python depends on the libstdc++ and does not work with libc++?

**Comment by sogaiu** [comment]
I don't have any good answers to either of your additional questions.

Perhaps someone else does though.

**Comment by sogaiu** [comment]
Looks like the code you pointed out was added here: https://github.com/tree-sitter/py-tree-sitter/commit/3967670cac60386c69345224d46dae8df956c3c2

May be @maxbrunsfeld can shed some light on this.

**Comment by maxbrunsfeld** [comment]
It looks like python’s build utils couldn’t find your libstdc++ library while building the language library. Probably we should throw an exception in that situation inside of Language.build_library.

**Comment by robobenklein** [comment]
I don't think it can't find the library, but it simply isn't being included somehow:

```python
>>> from ctypes.util import find_library
>>> find_library('stdc++')
'libstdc++.so.6'
```

**Comment by solsane** [comment]
Same issue here. PopOS! 20.04. 
```bash
ldd ~/.cache/wsyntree/python/language.so
	linux-vdso.so.1 (0x00007ffd26ce5000)
	libc++.so.1 => /lib/x86_64-linux-gnu/libc++.so.1 (0x00007f6d2ac46000)
	libc++abi.so.1 => /lib/x86_64-linux-gnu/libc++abi.so.1 (0x00007f6d2ac0e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6d2abf3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6d2aa01000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6d2a9de000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6d2a88f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6d2a882000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6d2ad67000)
```

**Comment by robobenklein** [comment]
The following change resulted in the build and load working just fine:

```diff
diff --git a/tree_sitter/__init__.py b/tree_sitter/__init__.py
index cc94ac9..38fe7a4 100644
--- a/tree_sitter/__init__.py
+++ b/tree_sitter/__init__.py
@@ -44,10 +44,8 @@ class Language:
 
         compiler = new_compiler()
         if cpp:
-            if find_library("c++"):
-                compiler.add_library("c++")
-            elif find_library("stdc++"):
-                compiler.add_library("stdc++")
+            compiler.add_library("c++")
+            compiler.add_library("stdc++")
 
         if max(source_mtimes) <= output_mtime:
             return False
```

I have both libraries, but I'm not sure if everyone else will. Would the following be fine?

```diff
diff --git a/tree_sitter/__init__.py b/tree_sitter/__init__.py
index cc94ac9..8f4ed6b 100644
--- a/tree_sitter/__init__.py
+++ b/tree_sitter/__init__.py
@@ -46,7 +46,7 @@ class Language:
         if cpp:
             if find_library("c++"):
                 compiler.add_library("c++")
-            elif find_library("stdc++"):
+            if find_library("stdc++"):
                 compiler.add_library("stdc++")
 
         if max(source_mtimes) <= output_mtime:
```

I wonder if the two libs might conflict in other tree sitter languages. Whatever the case is, it's true that this issue only shows up for some specific languages (i.e. happened for python, but no problem for javascript).

**Comment by eyepatchParrot** [comment]
My fix was to simply reverse the order of libc++ and libstdc++. I do have to wonder if py-tree-sitter is compatible with libc++.

**Comment by kamadorueda** [comment]
I found the same issue when trying to do build_library with two grammars:
- one which requires to be built with C (java)
- other with C++ (php)

they cannot coexist into the same build_library, so you have to generate two different .so files for each one
