### ISSUE TITLE
Python crash when executing parser.set_language(XX_LANGUAGE)

### ISSUE THREAD

**Issue by SergioShen** [tree-sitter/py-tree-sitter#42]
I'm using python 3.7 in Windows. My python program will always crash when executing parser.set_language(XX_LANGUAGE) no matter what language I'm binding to the parser. This issue won't occur in Linux or macOS but always do in Windows.

**Comment by maxbrunsfeld** [comment]
I think this is a duplicate of #18.

Sorry for the poor experience; I'd definitely like to address it, but don't use windows normally and don't have the time to debug it right now.
