### ISSUE TITLE
Support memoryview inputs in addition to bytes inputs

### ISSUE THREAD

**Issue by leezu** [tree-sitter/py-tree-sitter#48]
A memoryview object exposes the C level buffer interface as a Python object which can then be passed around like any other object. https://docs.python.org/3/c-api/memoryview.html

I have a pyarrow table of [strings](https://arrow.apache.org/docs/python/generated/pyarrow.StringScalar.html) where each string contains the content of a source code file.
Pyarrow exposes each row as [pyarrow.Buffer](https://arrow.apache.org/docs/python/generated/pyarrow.Buffer.html), which is compatible with the Python memoryview interface.

It would be nice if tree-sitter can be executed directly on the memoryview, instead of requiring users to perform a copy to a new `bytes` object

Example:

```
    parser = tree_sitter.Language(lib_path, 'python')
    parser.parse(memoryview(tbl['content'][0].as_buffer()))  # TypeError: First argument to parse must be bytes
    parser.parse(tbl['content'][0].as_buffer().to_pybytes())  # Works, but performs unnecessary copy.
```

**Comment by maxbrunsfeld** [comment]
This would be a great feature. Are you interested in opening a PR adding support for this?

**Comment by leezu** [comment]
I'll submit a PR soon, thank you
