### ISSUE TITLE
Expose full public API into python

### ISSUE THREAD

**Issue by brupelo** [tree-sitter/py-tree-sitter#7]
This file [api.h](https://github.com/tree-sitter/tree-sitter/blob/4d4e4f3909358bb5abdc3c3de0640d1b4ff444fe/lib/include/tree_sitter/api.h) contains the public tree-sitter API, right? So, shouldn't be that fully exposed into python?

Which leads me to another question, the way you've created the wrapper is really nice (it's minimal and user friendly), also dependency-free but... why didn't you consider using [cffi](https://cffi.readthedocs.io/en/latest/overview.html#main-mode-of-usage), [swig](http://www.swig.org/) or similars? Was it because you didn't want to add any dependency or any other reason?

**Comment by brupelo** [comment]
I've created a swig wrapper... if you want to try, follow the below steps:

- Download swig and make it available on path
- tree_sitter\tree_sitter.i:

        %module tree_sitter

        %{
        #include "tree_sitter/api.h"
        #include "tree_sitter/parser.h"
        %}

        %include "tree_sitter/api.h"
        %include "tree_sitter/parser.h"

- modify `setup.py` and change the existing Extension object by this one:

        Extension(
            "_tree_sitter",
            [
                "tree_sitter/core/lib/src/lib.c",
                "tree_sitter/tree_sitter.i"
            ],
            include_dirs = [
                "tree_sitter/core/lib/include",
                "tree_sitter/core/lib/utf8proc",
            ],
            swig_opts = [
                "-Itree_sitter/core/lib/include",
                "-Itree_sitter/core/lib/utf8proc",
            ],
            extra_compile_args = (
                ['-std=c99'] if platform.system() != 'Windows' else None
            )
        )

- Reinstall again and if everything went fine you should get the **full public API** available:

    >>> import _tree_sitter
    >>> dir(_tree_sitter)

Easy peasy, full public API for free always up-to date with tree-sitter C... only inconvenience is what I've already mentioned in my first post... you've coupled the project with SWIG :)

PS. I think the fact you've coded your API as a C library and not C++ has been a realy good decission, in my experience wrapping c++ libs on python is more tedious

**Comment by brupelo** [comment]
Btw, the above attempt isn't very usable atm... if you try to install that, only the shared library generated by swig would be copied but not the wrapper (which imports the shared library).

I've decided opening a question about this fact on SO, [https://stackoverflow.com/questions/56562132/setup-py-not-installing-swig-extension-module](https://stackoverflow.com/questions/56562132/setup-py-not-installing-swig-extension-module) in the meantime :/

**Comment by brupelo** [comment]
Ok, I've decided to create a full example to show one possible way that SWIG integration could be done.

Please check this one [https://github.com/brupelo/pytreesitter](https://github.com/brupelo/pytreesitter)... As you can see, after installing that stuff you should get the whole API (private+public) of tree-sitter in python...

That said, I already got again stuck :/ , maybe you can bring some light to this... I'm trying to figure out how to make the cast to (TSLanguage*) in this line [https://github.com/brupelo/pytreesitter/blob/master/test/test.py#L18](https://github.com/brupelo/pytreesitter/blob/master/test/test.py#L18), in py-tree-sitter you do [https://github.com/tree-sitter/py-tree-sitter/blob/master/tree_sitter/binding.c#L261](https://github.com/tree-sitter/py-tree-sitter/blob/master/tree_sitter/binding.c#L261)

One litte aside note, that repo is just to illustrate the possible usage of swig, maybe you were already familiar with SWIG when you decided to create the existing wrapper and you already considered the pros/cons of picking up the existing route. Anyway, in #5 you told me TSCursor wasn't exposed and that was one of the keys to get performant highlighting, that's why i explored this route.

Btw, could you clarify what's the public API? is it the whole bunch of functions/structures living in both `api.h` and `parser.h` files?

**Comment by maxbrunsfeld** [comment]
The public API is the content of `api.h`. The `parser.h` file is used when compiling generated parsers; none of its definitions are part of the public API.

> I've decided to create a full example to show one possible way that SWIG integration could be done.

That's cool, I'll be interested to see how that works out. Maybe ping me if you get it to the point where you have some passing unit tests so I can look at the tests and see how the generated Python API works.

I have never used SWIG before, but I have used some other binding-generation tools for dynamic languages. My overall opinion is that for Tree-sitter, where performance is a major feature and the API is pretty small (just a couple of "classes", and fairly few methods each), it's not worth it to use a tool like that. I feel like writing the bindings by hand will lead to a cleaner, better module. Also, we don't always want a 1:1 mapping of C functions to Python methods. We can make the module more idiomatic by using things like optional keyword arguments.

I don't think that it's too much work to add the remaining bindings for TreeCursor and any remaining Tree-sitter APIs. Python is already designed to make C integration very easy. I haven't gotten around to it yet, but I feel like it could pretty much follow the existing patterns.

That said, maybe I'm underestimating SWIG!

**Comment by brupelo** [comment]
Hey Max, what you're saying makes total sense, I'm not a guru using SWIG neither but I've used it on few personal project in the past, creating wrappers with SWIG is usually really easy and convenient, specially when dealing c++ code, you end up getting quite pythonic code straightaway. The problem I've faced though is the generated wrappers will add some overhead and the performance won't be as good as one could expect, probably not even that performant as using well crafted manual wrappers.

So yeah, I think the strategy you've picked up here is reasonable and correct, (probably faster module & dependency-free in comparison to SWIG).

> That's cool, I'll be interested to see how that works out. Maybe ping me if you get it to the point where you have some passing unit tests so I can look at the tests and see how the generated Python API works.

For the time being I think I'll stop playing with the swig module, that was just a little experiment to see if everything would work out of the box but it seems it requires some extra tweaking (see the question of my previous comment for example)... right now my main goal is creating a GLSL highlighter with QScintilla and py-tree-sitter should allow me to achieve that already... maybe eventually once this goal is achieved I come back to play a little bit more with the other one (highly unlikely though), create unit tests, check performance, etc.

> I don't think that it's too much work to add the remaining bindings for TreeCursor and any remaining Tree-sitter APIs. Python is already designed to make C integration very easy. I haven't gotten around to it yet, but I feel like it could pretty much follow the existing patterns.

This would be awesome! as I said, right now I'll try to create a naive highlighter using normal tree traversal but probably at certain point I'll need this when dealing with large files... it'll be interesting to compare how TreeCursors will be an improvement in comparison to the naive approach

> That said, maybe I'm underestimating SWIG!

No, you're not :) , [https://news.ycombinator.com/item?id=2937247](https://news.ycombinator.com/item?id=2937247), read the mail of the SWIG author hehe. 

I think overall your choice of creating the wrapper here has been actually correct here. So I think the smartest thing will be continue improving the current repo with the current strategy used.

**Comment by maxbrunsfeld** [comment]
Ok, version 0.0.7 contains the `TreeCursor` API as well as the `Tree.edit` method, which makes it possible to do incremental parsing. These are all of the *major* pieces of Tree-sitter's functionality. There are probably still a few things that we can add as needed.

**Comment by brupelo** [comment]
Great, let's see how it goes, API looks really clean :)

> There are probably still a few things that we can add as needed.

One thing I've learned over the past years after coding thousand of hundreds of lines of code that I'd "probably" use/need in the future is... don't! :) . I mean, unless new use-cases are clear as water keep it minimal and as simple as possible... in fact, if something isn't very commonly used don't be afraid of getting rid of it to make the library as lightweight as possible :) 

Ps. My previous comment doesn't apply if your lib has already become a dep of customers paying for it ($$$) ;)

**Comment by CountryTk** [comment]
@brupelo Did you figure out how to do a DFS search on the syntax tree to gather all the missing information? I'm also making an IDE in python.

If you have an email or discord then please let me know, I'd like to talk about topic concerning IDE's

**Comment by brupelo** [comment]
@brupelo Hi, when Max had provided the TreeCursor API I was really happy but because lack of time I haven't tried yet the new exposed API. Although at that point I knew py-tree-sitter was "ready to go", so it's basically just a matter of using the API :)

Right now on my tools I'm using qscintilla/pygments as a combo, you can check some basics here https://stackoverflow.com/questions/55775837/pygments-in-qscintilla , unfortunately that code it's completely unoptimized and it won't work well on large files, as you can see in that thread I've never got any good answer solving the proposed problem. Plus, even if pygments has support for many [languages](http://pygments.org/languages/) and became optimized the provided highlighting would still be really bad because the limitations of regular expressions, so switching to tree-sitter is definitely something I intend to do in the next coming weeks/months when I find the time, reason I haven't done so is because there aren't any GLSL parser available so probably I'd have to create my own parser, yet another reason I'm waiting to see if somebody else will create it :D

Talking about IDEs in python. Unfortunately, choices of having an state of the art editor on python are really limited right now. At this point I'm using QScintilla but I don't really like that component for many reasons, when compared to SublimeText or CodeMirror I find it lacking a lot of important features... but actually, there  aren't many good alternatives to use with pyqt/pyside2, here's some links:

    https://github.com/ajaxorg/ace
    https://github.com/andreikop/qutepart
    https://github.com/awm/synhtor/wiki/Research
    https://github.com/codemirror/CodeMirror
    https://github.com/edbee/edbee
    https://github.com/edbee/edbee-app
    https://github.com/edbee/edbee-data
    https://github.com/edbee/edbee-examples
    https://github.com/edbee/edbee-lib
    https://github.com/githole/Live-Coder
    https://github.com/howl-editor
    https://github.com/hydrargyrum/eye
    https://github.com/JuBan1/notepadqq
    https://github.com/JuBan1/OpenTextEdit
    https://github.com/kai66673/PythonEditor
    https://github.com/luchko/QCodeEditor
    https://github.com/lukedan/codepad
    https://github.com/martinrotter/textosaurus
    https://github.com/matkuki/ExCo
    https://github.com/prymatex/prymatex
    https://github.com/pybee/seasnake
    https://github.com/pyQode/pyqode.core
    https://github.com/richrd/suplemon
    https://github.com/SergeySatskiy/codimension
    https://github.com/smathot/QProgEdit
    https://github.com/spyder-ide/spyder
    https://github.com/trishume/syntect
    https://github.com/tsujan/FeatherPad
    https://github.com/waddlesplash/Heidi
    https://kate-editor.org/
    https://sourceforge.net/projects/synwrite

I'd thought about coding my own custom opengl text editor ready to use on python but that sort of project would involve few months and I don't have the time for it... So at this point I think a combo of QScintilla+py-tree-sitter wouldn't be a bad tradeoff with some limitations, I guess I can live with that.

> If you have an email or discord then please let me know, I'd like to talk about topic concerning IDE's

I just use the good old IRC, you can find me sometimes in #python@freenode or even better... we could create some unofficial channel about tree-sitter in freenode.

Just for the record, I'd already asked about [support](https://github.com/tree-sitter/tree-sitter/issues/356#issuecomment-500931263) few weeks ago and Max already said some forum would be created eventually... that'd be awesome. Hopefully this forum will be UI friendly so we can post code nicely like in github. Personally I do love [discourse](https://www.discourse.org/) based forums.

But yeah, topics concerning IDE's is something I really like to talk about... one project I'm really interesting with is [https://github.com/lukedan/codepad](https://github.com/lukedan/codepad), I thought about creating python bindings for that one when project matures a bit.

**Comment by CountryTk** [comment]
Since my CS knowledge is a bit limited, I don’t understand how I could do a dfs search without recursion

As for scintilla, I used to have it in my IDE but I decided to write the editor component my self 

And yeah regex based highlighting is slow, but I made my own syntax highlighter which highlights only what you can see but none of those changes are in my repo yet (www.github.com/countrytk/pypad)

I guess I’ll get an irc client and join freenode when I get home from work

**Comment by brupelo** [comment]
@CountryTk I think you definitely don't want to do tree-traversal using python directly but instead using tree-sitter instead... I guess that'll be much faster. In any case, a simple naive iterative dfs algorithm is 7 lines code in python, here's a little example:

    def dfs(graph, start):
        path = []
        q = [start]
        while q:
            v = q.pop(0)
            if v not in path:
                path = path + [v]
                q = graph[v] + q
        return path


    if __name__ == '__main__':
        graph = {
            'a': ['b', 'c'],
            'b': ['d', 'e'],
            'c': ['f'],
            'd': [],
            'e': ['f'],
            'f': []
        }

        for start in ['a', 'b', 'c', 'd', 'e', 'f']:
            print(f'dfs {start} => {dfs(graph, start)}')

So, I understand you're going to integrate tree-sitter as well in your project? Nice, please share link in this thread when it's done ;)

**Comment by CountryTk** [comment]
@brupelo

Well at first I was going to use the normal tree sitter library but I couldn’t get it successfully linked for my project so I decided I’ll do it in python first and then c++ since I have the same project that I have in python also written in c++ but with less features

Thanks for the code sample though

**Comment by maxbrunsfeld** [comment]
Ok, most of the API is now available, and implemented in a way that I like, so I'm going to close this one out. We can open new issues for specific API changes if needed.
