### ISSUE TITLE
Edit the AST and apply the changes back to text

### ISSUE THREAD

**Issue by bdqnghi** [tree-sitter/py-tree-sitter#70]
For example, i have this piece of code:
`
  // this is a comment
  fn main() {
  /* this is another
     comment
     */
  }
`

I traverse the AST to remove all of the comments, which expect to output this code:
`
  fn main() {
  }
`
The question is that I have the edited version of AST, but not sure how to convert the edited AST back to text ? What is the function to call?

**Comment by allomy** [comment]
Hi, @bdqnghi , have you solved this problem?
