### ISSUE TITLE
Obtain argument type from AST

### ISSUE THREAD

**Issue by ljiahao** [tree-sitter/py-tree-sitter#71]
Can tree-sitter support obtaining the argument type of callee function? I can use query mechanism to obtain the method_invocation Node, while I have no idea how to know the argument type of this invocated function. 

To confirm it, can we obtain the argument type from the AST.

Thanks.

**Comment by amaanq** [comment]
if the code has type hints, sure? You could query for them. If not, then no, tree-sitter is not a semantic analysis tool like an lsp/compiler might be.
