### ISSUE TITLE
{{ at the end of an f-string string doesn't parse

### ISSUE THREAD

**Issue by verhovsky** [tree-sitter/py-tree-sitter#73]
`{{` is used to write a literal "{" in an f-string, but it's not parsed correctly if it's at the end of the string

```py
f"{my_var} {{"
```

```
module [0, 0] - [1, 0]
  ERROR [0, 0] - [0, 14]
    interpolation [0, 2] - [0, 10]
      identifier [0, 3] - [0, 9]
```

Adding a space after the `{{` causes it to parses correctly:

```py
f"{my_var} {{ "
```

```
module [0, 0] - [1, 0]
  expression_statement [0, 0] - [0, 15]
    string [0, 0] - [0, 15]
      interpolation [0, 2] - [0, 10]
        identifier [0, 3] - [0, 9]
```

**Comment by lunixbochs** [comment]
These are the Python bindings. Are you looking for the Python grammar? https://github.com/tree-sitter/tree-sitter-python

**Comment by verhovsky** [comment]
sorry
