### ISSUE TITLE
unusual bug

### ISSUE THREAD

**Issue by kodonnell** [tree-sitter/py-tree-sitter#8]
Using python3.6 (in a clean conda env) + tree-sitter==0.0.7 in WSL, running below

```python
from tree_sitter import Language, Parser

Language.build_library("build/my-languages.so", ["vendor/tree-sitter-python"])

PY_LANGUAGE = Language("build/my-languages.so", "python")

parser = Parser()
parser.set_language(PY_LANGUAGE)

tree = parser.parse(
    bytes(
        """
from mymodule import f
a = f()
""",
        "utf8",
    )
)

cursor = tree.walk()

print(cursor.node.sexp())

print(dir(cursor))
print(cursor.node.type)

print(cursor.goto_first_child())
print(cursor.node.type)

print(cursor.goto_first_child())
print(cursor.node.type)
print(dir(cursor.node)) # X 
# print(cursor.node.is_named) #  Y
print(cursor.node.sexp())
print(cursor.node)

# Returns `False` because the `def` node has no children
print(not cursor.goto_first_child())

print(cursor.goto_next_sibling())
print(cursor.node.type)

print(cursor.goto_next_sibling())
print(cursor.node.type)
```

gives

```
...
Traceback (most recent call last):
  File "bug.py", line 34, in <module>
    print(cursor.node.sexp())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 1: invalid start byte
```

Can you also see this behaviour?

If you comment line `... # X` or uncomment line `... # Y`, there's no error. I know nothing about tree-sitter, and was just messing around (trying to see if tree-sitter follows imports, which it doesn't seem to) ... but I figure you'd want to know. My suspicion is that it's something related to the C binding ... but it's a pretty weird bug (including e.g. if you delete the remainder of the code after where it errors, it stops erroring ... which really baffles me unless this isn't synchronous?)

FYI, error is from [PyUnicode_FromString](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FromString) from [here](https://github.com/tree-sitter/py-tree-sitter/blob/41e92835f137379a27c2f257ee1529b4f0e63080/tree_sitter/binding.c#L72) - whatever `*string` is isn't `utf8`.

**Comment by maxbrunsfeld** [comment]
Thanks for the report and repro steps!

> If you comment line ... # X or uncomment line ... # Y, there's no error
> if you delete the remainder of the code after where it errors, it stops erroring

I'm not seeing either of these ☝️ behaviors. I can reproduce the bug with less code:

```py
from tree_sitter import Language, Parser

Language.build_library("build/my-languages.so", ["vendor/tree-sitter-python"])
PY_LANGUAGE = Language("build/my-languages.so", "python")
parser = Parser()
parser.set_language(PY_LANGUAGE)

tree = parser.parse(
    bytes(
        """
from mymodule import f
a = f()
""",
        "utf8",
    )
)

cursor = tree.walk()
print(cursor.goto_first_child())
print(cursor.goto_first_child())
print(cursor.node.sexp())
```

I believe this is a bug in the core Tree-sitter function that `sexp()` uses. Basically, `sexp` doesn't work for leaf nodes like `"from"` - it seems to return garbage in that case.
