### ISSUE TITLE
How to get some node's name?

### ISSUE THREAD

**Issue by killa1218** [tree-sitter/py-tree-sitter#80]
For example if we define `field('var_name', $.identifier);` in gramma.js. How can I get the name 'var_name' from an identifier node object?
There is a property `is_named` to indicate whether current node has name, but no something like `name` or `get_field_name()`.

**Comment by sogaiu** [comment]
If willing to use a cursor, may be the following sort of thing could work?

https://github.com/tree-sitter/py-tree-sitter/blob/b5dfe29b4ead51678bf72c5da47feaa56d4e2be1/tests/test_tree_sitter.py#L370
