### ISSUE TITLE
Distribute binary wheels with all languages?

### ISSUE THREAD

**Issue by grantjenks** [tree-sitter/py-tree-sitter#81]
I've used GitHub Actions in the past to distribute binary wheels. Would you be open to do that with py-tree-sitter?

Also, the current workflow for adding language support is hard to integrate with CI systems. For the sake of developer productivity, would it be possible to simply distribute all languages with the package by default?

**Comment by NorthIsUp** [comment]
I made this for the same purpose. Note this is not a binary wheel, but one that will compile tree-sitter-python on install. Would love to move it to this repo tho.

https://github.com/NorthIsUp/tree-sitter-python-language

**Comment by grantjenks** [comment]
# py-tree-sitter-languages

FYI I created https://github.com/grantjenks/py-tree-sitter-languages to distribute binary Python wheels with all tree-sitter languages supported.

## Install

`$ pip install tree_sitter_languages`

Source installs are not supported. To see how the binary wheels are built, look at:

1. setup.py — Python package setup.
2. build.sh — Shell script to download support for all languages.
3. build.py — Python script to build support for all languages.
4. .github/workflows/release.yml — GitHub action to invoke [cibuildwheel](https://github.com/pypa/cibuildwheel) and release to PyPI.

## Usage

```python
from tree_sitter_languages import get_language, get_parser

language = get_language('python')
parser = get_parser('python')
```

That's the whole API!

Refer to [py-tree-sitter](https://github.com/tree-sitter/py-tree-sitter) for the language and parser API. Notice the `Language.build_library(...)` step can be skipped! The binary wheel includes the language binary.

**Comment by lunixbochs** [comment]
I have a local branch that compiles languages directly into our library, I'm planning to put more work into that

**Comment by grantjenks** [comment]
Good point about licenses. I checked them this morning and included a list at the bottom of the README: https://github.com/grantjenks/py-tree-sitter-languages#license

**Comment by ObserverOfTime** [comment]
Parsers can now easily build wheels themselves with the updated bindings in https://github.com/tree-sitter/tree-sitter/commit/9e5bf6591fbf69f7cf79d178e4bcae98408bae40.

**Comment by DreamRunnerMoshi** [comment]
I am trying to install in MacBook, getting this error for Kotlin and Scala

` File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)`

Anyone face this kind of problem?

**Comment by Akuli** [comment]
You no longer need `tree_sitter_languages`, because this repo now does everything that it does, in an incompatible way.

Instead, you should use language-specific pypi packages, like `tree-sitter-python` for parsing Python code, but there isn't such package for scala yet. See #237.
