### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SherloqueChang** [tree-sitter/py-tree-sitter#86]
Hi, I want to install `tree-sitter-parser` python bindings to fix the error "no generator found" while invoking GumTree Java API to parse C code files. However, when I ran the command `pip3 install tree_sitter` in cmd, an error occured:`Could not build wheels for tree_sitter, which is required to install pyproject.toml-based projects`.
I have had a C compiler installed, and my python version is 3.9.7. I couldn't figure out why this didn't work. 
Your help is needed badly, thanks a lot.

**Comment by yanchvlad** [comment]
Hi, Did you find a solution? Thanks

**Comment by SherloqueChang** [comment]
I downloaded the `tar.gz` file from https://pypi.org/project/tree-sitter/#files and used `python setup.py install` to install `tree_sitter`.

However, I'm not sure if it would work for I didn't expect to parse/diff files using command line. So I didn't take further action.

If you seek to use GumTree, maybe using Docker image is a good idea.
