### ISSUE TITLE
Queries with multiple predicates fail with RuntimeError

### ISSUE THREAD

**Issue by ls-jad-elkik** [tree-sitter/py-tree-sitter#92]
Queries that contain two predicates seem to always fail with a RuntimeError with this message: `Capture predicate must start with a string`.

I tried digging deeper and got a minimal test that reproduces the issue on this PR https://github.com/tree-sitter/py-tree-sitter/pull/91 but I don't have a fix for it yet.

I see that this is a feature introduced recently in https://github.com/tree-sitter/py-tree-sitter/pull/82 and not published on PyPI yet.

Trying this in [the playground](https://tree-sitter.github.io/tree-sitter/playground) works as expected, so I'm thinking it has to be an issue in the Python bindings:

Code:
```javascript
keypair_object = {
    key1: value1,
    equal: equal
}

function fun1(arg) {
    return 1;
}

function fun1(notarg) {
    return 1 + 1;
}

function fun2(arg) {
    return 2;
}
```

Query:
```
(
    (function_declaration
        name: (identifier) @function-name
        parameters: (formal_parameters
            (identifier) @argument-name
        )
    )
    (#eq? @function-name fun1)
    (#eq? @argument-name arg)
)
```

I expect it to match `fun1(arg)` only - which seems to be the case in the playground (only that line's function/argument names are coloured).

cc @ocastejon since you were the author of that PR - would you have any hints/clues about the root cause?

**Comment by ocastejon** [comment]
Let me take a look at it, it should not be too difficult to find the root cause!

**Comment by ocastejon** [comment]
Ok, luckily the bug is pretty straightforward to fix. I'll add the details as a comment in #91, but let me know if you need anything else from me.

**Comment by ls-jad-elkik** [comment]
Thanks for your help! The last time I used pointer arithmetic was 5 years ago so it would have taken me some time to figure this one out 😄
