### ISSUE TITLE
node.is_named, what about node.name?

### ISSUE THREAD

**Issue by NorthIsUp** [tree-sitter/py-tree-sitter#96]
would the ts api support getting the name of a node?

**Comment by ubergarm** [comment]
possibly a duplicate of #80 

I've found the `text` field useful in my use-case to access the actual code bytes e.g.
```python
if (node.type == "function_definition"):
    print(node.text.decode("utf-8"))
```

**Comment by maxbrunsfeld** [comment]
`node.type`
